name: Example workflow

on: [push]

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: start minikube
        run: |
          # See more in "Installation" https://minikube.sigs.k8s.io/docs/start/
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          # Github Action limit cpu:2, memory: 6947MB, limit to 2U6G for better resource statistic
          minikube start --cpus 2 --memory 6144
      - name: Interact with the cluster
        run: |
          kubectl get serviceaccount
          kubectl create serviceaccount kyuubi
          kubectl create clusterrolebinding kyuubi-role --clusterrole=edit --serviceaccount=default:kyuubi
          kubectl get serviceaccount
      - name: start kyuubi
        run: kubectl apply -f https://raw.githubusercontent.com/apache/kyuubi/master/integration-tests/kyuubi-kubernetes-it/src/test/resources/kyuubi-server.yaml


