name: Example workflow

on: [push]

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.29.0'
          kubernetes version: 'v1.26.1'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: |
          sleep 30s && kubectl get node
          kubectl get serviceaccount
          kubectl create serviceaccount kyuubi
          kubectl create clusterrolebinding kyuubi-role --clusterrole=edit --serviceaccount=default:kyuubi
          kubectl get serviceaccount
      - name: start kyuubi
        run: kubectl apply -f https://raw.githubusercontent.com/apache/kyuubi/master/integration-tests/kyuubi-kubernetes-it/src/test/resources/kyuubi-server.yaml
      - name: kyuubi pod check
        run: |
          kubectl get pods
          kubectl describe pods kyuubi-test

