name: Example workflow

on: [push]

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          cache: false
          minikube-version: 1.29.0
          driver: docker
          container-runtime: containerd
          kubernetes-version: v1.26.1
      - name: Interact with the cluster
        run: 'sleep 30s && kubectl get nodes'
