name: CI

on: [push]

env:
  KUBERNETES_VERSION: v1.26.1
  MINIKUBE_VERSION: v1.29.0

jobs:
  default:
    name: yum-with-browser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          # passthrough CI into build container
          context: .
          file: Dockerfile
          load: false
          tags: runzhliu/yum-with-browser:latest
          push: true
      - name: Setup Minikube
        run: |
          # https://minikube.sigs.k8s.io/docs/start/
          curl -LO https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --cpus 2 --memory 4096 --kubernetes-version=${KUBERNETES_VERSION} --force
          # https://minikube.sigs.k8s.io/docs/handbook/pushing/#7-loading-directly-to-in-cluster-container-runtime
          minikube image load runzhliu/yum-with-browser:latest
      - name: kubectl pre-check
        run: |
          kubectl get nodes
          kubectl get node
          kubectl apply -f yum-with-browser.yaml